- name: Listen for events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: "Act on - state: provisioning"
      condition: event.payload.state == "provisioning"
      action:
        run_playbook:
          name: playbooks/1-test.yaml